/**
 * The physical-name token editor — plan §4.14, artboard S8, inventory §4 "Physical-name tokens".
 *
 * > `tensor`: a physical-name token editor (tokens: literal string, `{index}`, `{coordinate}` —
 * > **the three item forms of `physical_name`**), with the evaluated names for the current preview
 * > index shown beneath.
 *
 * A physical name is an array of three item forms, and this module is the *model* of the chips S8
 * draws: one row per item, with the form it is in, the text it carries and the names that form may
 * carry. Nothing of the three forms is written here. They are the walker's own answer over the
 * item's `oneOf` ({@link formOf}, feature 2.3): two alternatives are a closed object with one
 * scalar member, so the walker labels them by their discriminating key and edits them on the row;
 * the third is a bare string, which the walker labels by its declared type. A grammar that grew a
 * fourth item form would appear here as a fourth chooser option with no line changing.
 *
 * **What a chip is coloured by is a fact, not a word.** S8 draws a literal, an index and a
 * coordinate in three colours, and the difference between the last two is what the core answers
 * (`TokenNames.declared`): a composition index is a declaration of the document — §4.21's
 * structural colour — and a `stack`'s coordinate is generated by the stack, which is §4.21's
 * "derived, never declared". The interface reads that flag; it never reads the member's name.
 *
 * **Nothing is refused.** A token may name an index the rule does not fire under, and the names
 * beside the field are a suggestion (Q5, and feature 2.12's own reading of §4.15): V1 and V17 are
 * what say so, in Problems, with the pointer of the row.
 */
import { isJsonArray, type JsonValue, type TokenNames } from '@tensorspine/lang';
import type { Shape } from '@tensorspine/store';

import { factsOfShape, formOf, type FormContext, type FormMode } from '../forms/index.js';
import { itemShape } from './skeleton.js';

/**
 * The editor §4.14 owns, by the name `presentation.json` binds it under.
 *
 * Named here and nowhere else in the interface, beside the editor it names — the pattern
 * `widget.ts` and `expressions/language.ts` follow. It is no word of the four schemas: it is the
 * presentation file's own, and the audit holds that file to a schema listing it.
 */
export const TOKEN_LIST = 'token-list';

/** Whether a widget is that editor: what tells a physical name from any other list. */
export function editsTokens(widget: string | undefined): boolean {
  return widget === TOKEN_LIST;
}

/** One item form a token may take: the alternatives of `physical_name`'s item. */
export interface TokenForm {
  /** What labels it — a discriminating required key, or the declared type of an untagged one. */
  readonly tag: string;
  /** The member a name is written under, or `null` where the form is the scalar itself. */
  readonly member: string | null;
  /** The names the core offers for that member, empty where it offers none. */
  readonly names: readonly string[];
  /**
   * Whether those names are declared by the document, generated by the location, or neither.
   *
   * `null` for the form that carries no name at all — a literal is text the author writes.
   */
  readonly declared: boolean | null;
}

/** One token of a physical name, as a chip draws it. */
export interface TokenRow {
  /** Its position in the array, which is where an edit writes. */
  readonly at: number;
  /** The form it is in, by the walker's own label; `''` where the value matches no alternative. */
  readonly form: string;
  /** The member its name is written under; `null` for a literal. */
  readonly member: string | null;
  /** What it carries: the literal string, or the name. */
  readonly text: string;
  /** The names offered for this form. */
  readonly names: readonly string[];
  /** What colours the chip — see the module's note. */
  readonly declared: boolean | null;
}

/** A physical name as the editor holds it: its tokens, and the forms one may take. */
export interface TokenModel {
  readonly tokens: readonly TokenRow[];
  readonly forms: readonly TokenForm[];
  /** How few items the schema admits — `minItems`, which is what disables the last removal. */
  readonly least: number;
}

/** What the core answers about the names a token form may carry (§4.14). */
export type TokenOffers = readonly TokenNames[];

/** The tokens of one physical name, with the forms its items admit. */
export function tokenModel(
  context: FormContext,
  shape: Shape,
  value: JsonValue | undefined,
  offers: TokenOffers = [],
): TokenModel {
  const items = value !== undefined && isJsonArray(value) ? value : [];
  const forms = formsOf(context, shape, offers);
  const tokens = items.map((item, at) => tokenOf(context, shape, item, at, forms));
  return { tokens, forms, least: leastOf(shape) };
}

/** The value one token would be written as in a form, carrying the text it already has. */
export function tokenValue(form: TokenForm, text: string): JsonValue {
  return form.member === null ? text : { kind: 'object', members: [{ name: form.member, value: text }] };
}

/** The physical name with one token's text changed. */
export function withText(
  model: TokenModel,
  value: JsonValue | undefined,
  at: number,
  text: string,
): JsonValue {
  const row = model.tokens[at];
  const form = model.forms.find((one) => one.tag === row?.form) ?? model.forms[0];
  if (form === undefined) return itemsOf(value);
  return written(value, at, tokenValue(form, text));
}

/** The physical name with one token put into another form, its text carried over. */
export function withForm(
  model: TokenModel,
  value: JsonValue | undefined,
  at: number,
  tag: string,
): JsonValue {
  const form = model.forms.find((one) => one.tag === tag);
  if (form === undefined) return itemsOf(value);
  const text = model.tokens[at]?.text ?? '';
  return written(value, at, tokenValue(form, text));
}

/**
 * The physical name with one token more, at the end — S8's `+ token`.
 *
 * The new one is a **literal**, the first form the schema admits, and it is empty: what a blank
 * is, is "the first value the *grammar* accepts there" (feature 2.3's rule), and the grammar's own
 * `minLength` then reports the empty one on the row — D5's arrangement, and feature 2.12's `Add
 * input` precedent.
 */
export function withToken(model: TokenModel, value: JsonValue | undefined): JsonValue {
  const form = model.forms[0];
  if (form === undefined) return itemsOf(value);
  return [...itemsOf(value), tokenValue(form, '')];
}

/** The physical name with one token removed. */
export function withoutToken(value: JsonValue | undefined, at: number): JsonValue {
  return itemsOf(value).filter((_, index) => index !== at);
}

/** The array a physical name is, whatever the place currently holds. */
function itemsOf(value: JsonValue | undefined): readonly JsonValue[] {
  return value !== undefined && isJsonArray(value) ? value : [];
}

/** The array with one item replaced. */
function written(value: JsonValue | undefined, at: number, item: JsonValue): readonly JsonValue[] {
  const items = [...itemsOf(value)];
  if (at < 0 || at >= items.length) return [...items, item];
  items[at] = item;
  return items;
}

/**
 * The forms an item admits: the walker's alternatives, with the names the core offers for each.
 *
 * The item's own shape is stepped into once — every item of an array has the same definition — and
 * a form with no written value is what a chooser offers, which is exactly the list S8's chip menu
 * needs.
 */
function formsOf(context: FormContext, shape: Shape, offers: TokenOffers): TokenForm[] {
  const item = itemShape(context, shape, 0);
  const form = formOf(context, { shape: item, label: '', limit: 1 });
  const modes = form.rows[0]?.modes ?? [];
  return modes.map((mode) => formWith(mode, offers));
}

/** One alternative as a form, with what the core says its names are. */
function formWith(mode: FormMode, offers: TokenOffers): TokenForm {
  const member = mode.inline && mode.member !== undefined ? mode.member : null;
  const offered = member === null ? undefined : offers.find((one) => one.member === member);
  return {
    tag: mode.tag,
    member,
    names: offered?.names ?? [],
    declared: offered === undefined ? null : offered.declared,
  };
}

/** One written item as a row: which form it is, by the grammar's own verdict, and what it holds. */
function tokenOf(
  context: FormContext,
  shape: Shape,
  item: JsonValue,
  at: number,
  forms: readonly TokenForm[],
): TokenRow {
  const row = formOf(context, { shape: itemShape(context, shape, at), value: item, label: '', limit: 1 })
    .rows[0];
  const form = forms.find((one) => one.tag === row?.mode);
  return {
    at,
    form: row?.mode ?? '',
    member: form?.member ?? null,
    text: textOf(item, form?.member ?? null),
    names: form?.names ?? [],
    declared: form?.declared ?? null,
  };
}

/** What a token carries: the member's value where it has one, the scalar itself where it does not. */
function textOf(item: JsonValue, member: string | null): string {
  if (member === null) return typeof item === 'string' ? item : '';
  if (typeof item !== 'object' || item === null || isJsonArray(item) || item.kind !== 'object') {
    return '';
  }
  const held = item.members.find((one) => one.name === member)?.value;
  return typeof held === 'string' ? held : '';
}

/**
 * `minItems` at the place, which is how few tokens a name may have.
 *
 * Read through the walker's own facts rather than off the place's `direct` nodes: a physical name
 * is reached through an alternative of `location`, so the place has no direct reading at all and
 * the chain is where `minItems: 1` is written (feature 2.3's fallback, the same one the row's
 * bounds take).
 */
function leastOf(shape: Shape): number {
  return factsOfShape(shape).minItems ?? 0;
}
