"""The edited documents the `expansion` step records (feature 1.7).

`d1.emit` is a short function with a long reach, and most of it the repository exercises: the
corpus and the 73 documents of `tests/rejections/models/` reach every guard of a composition site,
the whole template expansion of `shieldstral-3b-composite`, the record defaults (309 fills over the
corpus), the `across_positions` condition in both its trivial and its argument-reading form, and
six of the places it raises — an undecidable binding guard, an undecidable site guard, a primitive
the base does not hold, an edge whose destination is not a node, a scoped-binding refusal and a
duplicate member name.

What nothing in the repository reaches, measured:

  * a **root** instance with a `when` at all — every guard of every corpus document is on a
    composition site, so the branch that keeps a root instance, the one that remembers it absent,
    and the refusal of an undecidable root guard are all unvisited;
  * a composition with **two indices** — none exists (finding F8), so `[half=0,layer=0]` and the
    grid's product order are never written;
  * a **value cycle**, so D1's own V6 refusal is never printed (V6 has no rejection fixture either,
    feature 1.6b's finding);
  * an **undecidable `across_positions`** — the fact D1 refuses to guess;
  * a **record argument that is not a record**, which `_record_defaults` steps over;
  * a template instance whose **`weights_location_prefix` does not evaluate**, and one a guard
    removes before it is ever expanded.

So beside the repository's own documents the step records *edited* ones, in the idiom features
1.3–1.6 established: each case is a list of edits at JSON pointers into a repository file, and
both implementations apply the same edits to the same bytes — neither side owns the input.

Every case is built on a **shortened** document, as feature 1.6c's are: `llama3-8b` with its
decoder cut to two layers, `voxtral-realtime` with both compositions cut to two, and
`shieldstral-3b-composite` with its vision composition and the template's `layers` cut to two —
which is the one place a shortening reaches *through* a template instance, the template's `layers`
being an external quantity the instance's argument supplies. Shortening is itself a case (`short`,
`vox-short`, `composite-short`), so the fixture states that the base each case edits is clean.

What no edit of a repository document can reach, because the reference base declares nothing that
would: a record field whose `default` is guarded by a `present_when` (none of the three defaulted
fields of the base carries one), a default that resolves to nothing or to `None`, a template
primitive citing a second one (the base holds exactly one template primitive, so nesting below
depth 1, `MAX_DEPTH` and the `primitive cycle` refusal have no document), and a template instance
generated by a composition, whose prefix is evaluated in the site's own indices. Those are the
unit suite's, over a base built for them.
"""

LLAMA = 'data/models/llama3-8b.json'
VOXTRAL = 'data/models/voxtral-realtime.json'
COMPOSITE = 'data/models/shieldstral-3b-composite.json'
TEMPLATE = 'data/models/decoder-causal-yarn/1.0.0.json'


def _set(pointer, value):
    return {'pointer': pointer, 'op': 'set', 'value': value}


# `llama3-8b`'s decoder runs `layer` over the literal 0..32 and its `final_n` edge names
# `layers - 1`, so both move together (feature 1.6c's reading of the design canvas's erratum E10).
SHORT = [
    _set('/compositions/decoder/indices/layer/stop/literal', 2),
    _set('/quantities/layers/source/value', 2),
]

# `voxtral-realtime` has two compositions and names each one's length as a quantity.
VOX = [
    _set('/compositions/encoder/indices/layer/stop/literal', 2),
    _set('/compositions/decoder/indices/layer/stop/literal', 2),
    _set('/quantities/enc_layers/source/value', 2),
    _set('/quantities/dec_layers/source/value', 2),
]

# The composite's own `vision` composition, and — through the template instance's `layers`
# argument — the template's decoder: an external quantity of the template, supplied at the call
# site, so the expansion shortens with the caller.
COMPOSITE_SHORT = [
    _set('/compositions/vision/indices/layer/stop/literal', 2),
    _set('/quantities/vit_layers/source/value', 2),
    _set('/quantities/layers/source/value', 2),
]

# An external quantity nothing assigns: what makes a guard, an argument or a condition undecidable
# without taking the document off the grammar.
UNSET = _set('/quantities/unset',
             {'type': {'kind': 'cardinality'}, 'source': {'kind': 'external'}})


def _reads_unset():
    return {'compare': {'operator': 'equal',
                        'left': {'quantity': 'unset'},
                        'right': {'literal': 1}}}


CASES = [
    # The shortened documents themselves: each case's base, and clean.
    ('short', LLAMA, []),
    ('vox-short', VOXTRAL, []),
    ('composite-short', COMPOSITE, []),

    # A root instance's guard: kept, removed, undecidable.
    ('root-guard-true', LLAMA, [_set('/instances/lm_head/when', {'boolean': True})]),
    ('root-guard-false', LLAMA, [_set('/instances/lm_head/when', {'boolean': False})]),
    ('root-guard-unresolved', LLAMA, [UNSET, _set('/instances/lm_head/when', _reads_unset())]),

    # A composition over two indices: `[half=0,layer=0]`, the identifier's names in order, and the
    # product of the grid. The two top-level bindings that name a generated site must name both
    # indices, or their edges would land on nodes that do not exist.
    ('two-index-composition', LLAMA, [
        _set('/compositions/decoder/indices/half',
             {'start': {'literal': 0}, 'stop': {'literal': 2}, 'step': {'literal': 1}}),
        _set('/bindings/values/decoder.entry/to/instance/indices/half', {'literal': 0}),
        _set('/bindings/values/decoder.entry.a/to/instance/indices/half', {'literal': 0}),
        _set('/bindings/values/final_n.in/from/instance/indices/half', {'literal': 0}),
    ]),

    # D1's own V6 refusal: the decoder's entry fed from the norm that reads its exit.
    ('value-cycle', LLAMA, [
        _set('/bindings/values/decoder.entry/from/instance',
             {'kind': 'root', 'instance': 'final_n'}),
    ]),

    # A record argument written as a scalar: `_record_defaults` steps over what is not a record.
    ('record-argument-scalar', LLAMA, [
        _set('/compositions/decoder/instances/attn/arguments/rope', {'literal': 3}),
    ]),

    # `conv_frontend`'s `across_positions` reads `kernel`; an argument that does not resolve makes
    # the fact undecidable, and D1 refuses rather than answering false.
    ('across-positions-undecidable', VOXTRAL, [
        UNSET, _set('/instances/conv_frontend/arguments/kernel', {'quantity': 'unset'}),
    ]),

    # A template instance a guard removes: never expanded, no `instances` entry, and the bindings
    # that named it dropped (§5.2 rule 3).
    ('template-guarded-out', COMPOSITE, [_set('/instances/text/when', {'boolean': False})]),

    # A prefix whose `{index}` names nothing at the call site.
    ('template-prefix-unresolved', COMPOSITE, [
        _set('/instances/text/weights_location_prefix', [{'index': 'nope'}]),
    ]),

    # A template read with no assignment at all. `--d1` never reaches it — `run` skips a document
    # `missing_assignment` reports on — but the editor does: a template opened on its own has no
    # graph until its preview assignment is supplied (§4.6, §5.5), and `Unassigned` is the refusal
    # that says so. It is a `ValueError`, so `d1.run`'s own catch would take it.
    ('template-without-assignment', TEMPLATE, []),
]

# Which shortening each case's source carries.
SHORTENED = {LLAMA: SHORT, VOXTRAL: VOX, COMPOSITE: COMPOSITE_SHORT, TEMPLATE: []}
