import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Where the oracle of the implementation plan's §0.5 lives, and what it writes.
 *
 * The parity suites of `packages/lang/test/parity/` compare the core with the repository's
 * `tools/`; the comparison material is generated by `pnpm oracle` (Python, CI and developer
 * machines only) into a directory this module names once for every suite.
 */

/** `editor/`, the workspace root. */
export const editorRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..');

/** The repository root: the corpus, the schemas, the primitive library and the fixtures. */
export const repositoryRoot = resolve(editorRoot, '..');

/** The oracle's generator, run by `pnpm oracle`. */
export const oracleGenerator = join(editorRoot, 'tests', 'oracle', 'generate.py');

/** The directory the generator writes; gitignored, regenerated, never committed. */
export const oracleOut = join(editorRoot, 'tests', 'oracle', 'out');

/** The manifest naming everything the generator wrote. */
export const oracleManifest = join(oracleOut, 'manifest.json');

/** One document of the corpus as the oracle recorded it. */
export interface OracleDocument {
  /** `llama3-8b` for a model, `decoder-causal-yarn@1.0.0` for a template version. */
  name: string;
  /** The document's path, relative to the repository root. */
  path: string;
  /** The external quantities a template was read under, `null` for a model. */
  assignment: Record<string, unknown> | null;
  /** D1, relative to the oracle's output directory. */
  d1: string;
  /** The derived document, relative to the oracle's output directory. */
  derived: string;
  /** The `--validate` output holding this document's line. */
  validate: string;
  /** The `--lint` output holding this document's findings. */
  lint: string;
}

/** What `generate.py` writes as `out/manifest.json`. */
export interface OracleManifest {
  generated_by: string;
  repository_commit: string | null;
  /** A digest over `tools/`, so that a recorded oracle can be told stale (plan §9 Q2). */
  tools_sha256: string;
  /** The same over `schemas/`. */
  schemas_sha256: string;
  python: string;
  /** `PYTHONHASHSEED` as the generator saw it; `null` when the interpreter randomised it. */
  python_hash_seed: string | null;
  jsonschema: string;
  documents: OracleDocument[];
  primitive_schemas: { directory: string; files: string[] };
  rejections: {
    models: string;
    primitive_library: string;
    documents: string[];
    bases: string[];
  };
  signatures: string[];
}

/** Whether `pnpm oracle` has been run in this working copy. */
export function oracleGenerated(): boolean {
  return existsSync(oracleManifest);
}

/** The oracle's manifest; call only when {@link oracleGenerated} answers true. */
export function readOracleManifest(): OracleManifest {
  return JSON.parse(readFileSync(oracleManifest, 'utf8')) as OracleManifest;
}
