import { describe, expect, it } from 'vitest';

import { d6, type PyRecord, type PyValue } from '../../src/index.js';
import { PyKeyError } from '../../src/expr/errors.js';
import { record, syntheticGraph, value, type SyntheticNode } from './source.js';

// D6 (feature 1.8e), stated directly: the branches of `derive.d6` no corpus document reaches.
//
// D6 is a function of four things — the expanded graph, D2's splits, D4's states and D1's
// published order — and of nothing else, so the honest unit test hands it all four. The products
// are written here as the tools write them, through the core's own parser, because the
// integer/float distinction is part of what D6 carries: an undeclared granularity is the *integer*
// one, a `span` is whatever D4 answered, and a byte figure is restated untouched.
//
// The parity suite settles what the corpus reaches: all five partition targets, all four
// communications and the one primitive admitting two, eight granularities, both kinds of split,
// the 21 separations of `gemma3n-kvshare` and the 1 208 information-loss rows. What it never
// reaches is here:
//
//   * a granularity that does not resolve, and one whose expression answers a boolean — `_num`
//     drops both, and the derived schema's nullable `granularity` is written for the first;
//   * a partition whose `when` fails, and a primitive that declares none at all;
//   * a writer on the *second* side, a writer that is not a member, a writer that is null, and a
//     separated identity whose evolution is not `window`;
//   * a slot whose `present_when` fails, an extent that is an `add` rather than a `multiply`, and
//     a flattened axis that declares its factors;
//   * a split D2 names that the structural walk does not, and a block that drops a node of the
//     order.

/** A definition with the `parameters` map `d6` subscripts, and whatever the case adds. */
function definition(parts: Record<string, unknown> = {}): PyValue {
  return record(JSON.stringify({ parameters: {}, ...parts }));
}

/** One root node of the scaffold, named and defined. */
function node(name: string, parts: Record<string, unknown> = {}): SyntheticNode {
  return { name, primitive: `demo.${name}`, definition: definition(parts) };
}

/**
 * The scaffold: three nodes in a chain, the first two generated by a composition of one index.
 *
 * `a → b → c`, with `a` and `b` sites of `decoder` at layers 0 and 1, so that the structural walk
 * names `decoder[layer<=0]` over the block `{a}` — the ancestor closure of the layer prefix — and
 * `c` stays outside it. The sites are root sites (their identifiers are `a`, `b`, `c`): D2 and D6
 * read a node's composition off `meta`, never off the key.
 */
function scaffold(nodes: readonly SyntheticNode[] = [node('a'), node('b'), node('c')]) {
  return syntheticGraph(nodes, [], {
    edges: [
      ['a.out', 'b.in'],
      ['b.out', 'c.in'],
    ],
    generated: { a: ['decoder', { layer: 0n }], b: ['decoder', { layer: 1n }] },
    compositions: ['decoder'],
    families: { a: ['attention'], b: ['attention'] },
  });
}

/** D2 as D6 reads it: one split, with the payload whose length is `crossing_values`. */
function splits(payload = 1, name = 'decoder[layer<=0]', kind = 'layer'): PyRecord {
  return record(
    JSON.stringify({
      graph_splits: [
        {
          graph_split: name,
          kind,
          sizes: [1, 2],
          payload: Array.from({ length: payload }, (_, index) => ({ value: `a.out${index}` })),
        },
      ],
    }),
  );
}

/** D4 as D6 reads it: the members of every state, and the figures a separation restates. */
function states(...entries: Record<string, unknown>[]): PyRecord {
  return record(
    JSON.stringify({
      states: entries.map((entry) => ({
        identity: 'kv',
        evolution: 'window',
        span: 4,
        bytes_per_cached_position: 8,
        sharing: 'within_span',
        writer: null,
        ...entry,
      })),
    }),
  );
}

/** D1's published order for the scaffold. */
const ORDER: readonly PyValue[] = ['a', 'b', 'c'];

/** D6 of the scaffold with those nodes, those splits and those states. */
function derived(
  nodes: readonly SyntheticNode[] = [node('a'), node('b'), node('c')],
  products2: PyRecord = splits(),
  products4: PyRecord = record('{"states": []}'),
  order: readonly PyValue[] = ORDER,
): PyRecord {
  return d6(scaffold(nodes), products2, products4, order);
}

/** The one graph split of an answer. */
function split(answer: PyRecord): PyRecord {
  const held = answer['graph_splits'] as readonly PyRecord[];
  expect(held).toHaveLength(1);
  return held[0] as PyRecord;
}

/** The separated states of the one graph split. */
function separated(answer: PyRecord): readonly PyRecord[] {
  return split(answer)['separated_states'] as readonly PyRecord[];
}

describe('the partition options of every node', () => {
  it('carries the target whole, the communication as a list and an undeclared granularity as one', () => {
    const answer = derived([
      node('a', {
        partition_options: [
          { target: { argument_axis: 'demo.width' }, communication: 'all_reduce' },
          {
            target: { payload_axis: { state: 'kv', component: 'k', axis: 'demo.head' } },
            communication: ['all_gather', 'all_reduce'],
          },
        ],
      }),
      node('b'),
      node('c'),
    ]);
    expect(answer['partition_options']).toEqual([
      {
        node: 'a',
        primitive: 'demo.a',
        target: { argument_axis: 'demo.width' },
        communication: ['all_reduce'],
        granularity: 1n,
      },
      {
        node: 'a',
        primitive: 'demo.a',
        target: { payload_axis: { state: 'kv', component: 'k', axis: 'demo.head' } },
        communication: ['all_gather', 'all_reduce'],
        granularity: 1n,
      },
    ]);
  });

  it('evaluates a declared granularity on the node’s own arguments', () => {
    const heads = {
      target: { argument_axis: 'demo.heads' },
      communication: 'all_reduce',
      granularity: {
        op: 'floor_divide',
        args: [{ argument: 'heads' }, { argument: 'kv_heads' }],
      },
    };
    const graph = syntheticGraph(
      [
        {
          name: 'a',
          primitive: 'demo.a',
          definition: definition({ partition_options: [heads] }),
          args: { heads: 32n, kv_heads: 8n },
        },
      ],
      [],
      {},
    );
    const answer = d6(graph, record('{"graph_splits": []}'), record('{"states": []}'), []);
    expect((answer['partition_options'] as readonly PyRecord[])[0]?.['granularity']).toBe(4n);
  });

  it('leaves a granularity the arguments do not decide, and a boolean one, blank', () => {
    // `_num(primitive_value(…))`: the sentinel and a boolean are both dropped, and the schema's
    // nullable `granularity` is what the first is written for. A primitive whose granularity cites
    // an argument that may be absent is admitted by the loader — the path is *declared*, and only
    // a *condition* over an optional argument needs a `present` test — so this is reachable from a
    // primitive declared in the editor (D15), never from the reference base.
    const options = [
      { target: { any_axis: true }, communication: 'none', granularity: { argument: 'absent' } },
      { target: { any_axis: true }, communication: 'none', granularity: { argument: 'flag' } },
    ];
    const graph = syntheticGraph(
      [
        {
          name: 'a',
          primitive: 'demo.a',
          definition: definition({ partition_options: options }),
          args: { flag: true },
        },
      ],
      [],
      {},
    );
    const answer = d6(graph, record('{"graph_splits": []}'), record('{"states": []}'), []);
    expect(
      (answer['partition_options'] as readonly PyRecord[]).map((row) => row['granularity']),
    ).toEqual([null, null]);
  });

  it('keeps a partition whose condition holds and drops one whose condition does not', () => {
    const guarded = (truth: boolean) => ({
      target: { none: true },
      communication: 'none',
      when: { boolean: truth },
    });
    const answer = derived([
      node('a', { partition_options: [guarded(true), guarded(false)] }),
      node('b'),
      node('c'),
    ]);
    expect(answer['partition_options']).toHaveLength(1);
  });

  it('gives a primitive that declares none no row at all', () => {
    expect(derived()['partition_options']).toEqual([]);
  });

  it('walks the nodes in the graph’s own order', () => {
    const one = { target: { any_axis: true }, communication: 'none' };
    const answer = derived([
      node('a', { partition_options: [one] }),
      node('b', { partition_options: [one] }),
      node('c', { partition_options: [one] }),
    ]);
    expect((answer['partition_options'] as readonly PyRecord[]).map((row) => row['node'])).toEqual([
      'a',
      'b',
      'c',
    ]);
  });
});

describe('the information loss of a flattened axis (O5.10)', () => {
  /** A slot whose one axis carries that extent, with whatever the case adds. */
  const slot = (extent: unknown, parts: Record<string, unknown> = {}) => ({
    shape: { axes: [{ name: 'f', axis: 'demo.flat', nature: 'feature', extent, ...parts }] },
  });
  const product = { op: 'multiply', args: [{ argument: 'heads' }, { argument: 'head_dim' }] };

  it('reports a product extent that declares no factors, naming the slot and the axis', () => {
    const answer = derived([node('a', { parameters: { w: slot(product) } }), node('b'), node('c')]);
    expect(answer['information_loss']).toEqual([
      {
        node: 'a',
        slot: 'w',
        axis: 'demo.flat',
        reason:
          'flattened axis without declared factors (O5.10): ' +
          'partitionability along its factors is unknown',
      },
    ]);
  });

  it('reports nothing for a product extent that declares its factors', () => {
    const factors = [
      { axis: 'demo.heads', extent: { argument: 'heads' } },
      { axis: 'demo.head_dim', extent: { argument: 'head_dim' } },
    ];
    const answer = derived([
      node('a', { parameters: { w: slot(product, { factors }) } }),
      node('b'),
      node('c'),
    ]);
    expect(answer['information_loss']).toEqual([]);
  });

  it('reports nothing for an extent that is not a product at all', () => {
    for (const extent of [
      { literal: 4096 },
      { argument: 'width' },
      { op: 'add', args: [{ argument: 'a' }, { argument: 'b' }] },
    ]) {
      const answer = derived([node('a', { parameters: { w: slot(extent) } }), node('b'), node('c')]);
      expect(answer['information_loss'], JSON.stringify(extent)).toEqual([]);
    }
  });

  it('skips a slot whose `present_when` does not hold on the node’s arguments', () => {
    const guarded = (truth: boolean) => ({
      ...slot(product),
      present_when: { boolean: truth },
    });
    expect(
      derived([node('a', { parameters: { w: guarded(false) } }), node('b'), node('c')])[
        'information_loss'
      ],
    ).toEqual([]);
    expect(
      derived([node('a', { parameters: { w: guarded(true) } }), node('b'), node('c')])[
        'information_loss'
      ],
    ).toHaveLength(1);
  });

  it('reports one row per flattened axis, in the slot’s and the axis’s declaration order', () => {
    const two = {
      shape: {
        axes: [
          { name: 'x', axis: 'demo.one', nature: 'feature', extent: product },
          { name: 'y', axis: 'demo.two', nature: 'feature', extent: { literal: 2 } },
          { name: 'z', axis: 'demo.three', nature: 'feature', extent: product },
        ],
      },
    };
    const answer = derived([
      node('a', { parameters: { w: two, v: slot(product) } }),
      node('b'),
      node('c'),
    ]);
    expect(
      (answer['information_loss'] as readonly PyRecord[]).map((row) => [row['slot'], row['axis']]),
    ).toEqual([
      ['w', 'demo.one'],
      ['w', 'demo.three'],
      ['v', 'demo.flat'],
    ]);
  });

  it('raises for a definition without a `parameters` map, as the subscript does', () => {
    const graph = syntheticGraph([{ name: 'a', definition: record('{}') }], [], {});
    expect(() =>
      d6(graph, record('{"graph_splits": []}'), record('{"states": []}'), []),
    ).toThrow(new PyKeyError("'parameters'"));
  });
});

describe('the graph splits', () => {
  it('carries D2’s name, kind and sizes, counts its payload and writes the block in D1 order', () => {
    const answer = derived(undefined, splits(3));
    expect(split(answer)).toEqual({
      graph_split: 'decoder[layer<=0]',
      kind: 'layer',
      sizes: [1n, 2n],
      crossing_values: 3n,
      block: ['a'],
      separated_states: [],
    });
  });

  it('writes a family block in D1 order, dropping the nodes the closure does not hold', () => {
    const answer = derived(undefined, splits(0, 'family:attention', 'family'));
    expect(split(answer)['block']).toEqual(['a', 'b']);
  });

  it('follows the published order, not the graph’s own', () => {
    // The block is `[n for n in order if n in block_ids]`: a reader of D1 finds the block in the
    // order D1 already gave them, whatever order the expansion built the closure in.
    const answer = derived(undefined, splits(0, 'family:attention', 'family'), undefined, [
      'c',
      'b',
      'a',
    ]);
    expect(split(answer)['block']).toEqual(['b', 'a']);
  });

  it('raises for a split D2 names that the structural walk does not', () => {
    expect(() => derived(undefined, splits(1, 'decoder[layer<=9]'))).toThrow(
      new PyKeyError("'decoder[layer<=9]'"),
    );
  });
});

describe('the state identities a split separates', () => {
  it('says nothing of an identity whose members are all on one side', () => {
    expect(separated(derived(undefined, splits(), states({ members: ['a.kv'] })))).toEqual([]);
    expect(
      separated(derived(undefined, splits(), states({ members: ['b.kv', 'c.kv'] }))),
    ).toEqual([]);
  });

  it('states the sides, the writer’s side and the far-side history of a `window` identity', () => {
    const answer = derived(
      undefined,
      splits(),
      states({ members: ['a.kv', 'b.kv', 'c.kv'], writer: 'a.kv' }),
    );
    expect(separated(answer)).toEqual([
      {
        identity: 'kv',
        evolution: 'window',
        span: 4n,
        bytes_per_cached_position: 8n,
        sharing: 'within_span',
        writer: 'a.kv',
        writer_side: 'first',
        first: ['a.kv'],
        second: ['b.kv', 'c.kv'],
        history_needed_by: ['b.kv', 'c.kv'],
      },
    ]);
  });

  it('puts the writer on the second side and takes the history from the first', () => {
    // Unreached by the corpus: `gemma3n-kvshare` writes its two shared identities at the earliest
    // layer that holds them, so every separation it produces has its writer first. A document whose
    // reader comes before its writer — a cross-attention cache filled after a layer that reads it —
    // is what this states, and the far side is then the *first* block, the writer excluded.
    const answer = derived(
      undefined,
      splits(),
      states({ members: ['a.kv', 'b.kv', 'c.kv'], writer: 'c.kv' }),
    );
    const held = separated(answer)[0] as PyRecord;
    expect(held['writer_side']).toBe('second');
    expect(held['history_needed_by']).toEqual(['a.kv']);
  });

  it('reads a null writer as the first side and asks history of the whole far side', () => {
    // V20 refuses a document whose identity nobody writes, so D4 never writes `writer: null` for a
    // document a derivation reaches — and the derived schema's `value_reference` would refuse it
    // anyway (feature 1.8b). `if s['writer']` is still a branch of the tools, and it is reproduced:
    // the writer is taken to be first, and every far member is asked for history.
    const held = separated(
      derived(undefined, splits(), states({ members: ['a.kv', 'b.kv'], writer: null })),
    )[0] as PyRecord;
    expect([held['writer_side'], held['history_needed_by']]).toEqual(['first', ['b.kv']]);
  });

  it('asks history of nobody for an identity that is not a `window`', () => {
    for (const evolution of ['append', 'fixed', null]) {
      const held = separated(
        derived(
          undefined,
          splits(),
          states({ members: ['a.kv', 'b.kv'], writer: 'a.kv', evolution }),
        ),
      )[0] as PyRecord;
      expect(held['history_needed_by'], String(evolution)).toEqual([]);
    }
  });

  it('raises for a writer that is not one of the members', () => {
    // What a writer stripped of the prefix its members carry would do (feature 1.8a's finding on
    // `shieldstral-3b-composite`): `sides[s['writer']]` is a subscript. Unreachable there, because
    // an identity inside a template instance has one member and is never separated.
    expect(() =>
      derived(
        undefined,
        splits(),
        states({ members: ['a.kv', 'b.kv'], writer: 'decoder/attn[layer=0].kv' }),
      ),
    ).toThrow(new PyKeyError("'decoder/attn[layer=0].kv'"));
  });

  it('lists the separated identities by name, whatever order D4 states them in', () => {
    const answer = derived(
      undefined,
      splits(),
      states(
        { identity: 'z.kv', members: ['a.kv', 'b.kv'], writer: 'a.kv' },
        { identity: 'a.kv', members: ['a.state', 'c.state'], writer: 'a.state' },
      ),
    );
    expect(separated(answer).map((state) => state['identity'])).toEqual(['a.kv', 'z.kv']);
  });

  it('reads a member’s side from its node, up to its *last* dot', () => {
    // `m.rsplit('.', 1)[0]`. No member of the repository tells the two readings apart: a node
    // identifier is a name or `<composition>/<site>[<index>=<value>]`, and neither carries a dot,
    // so a member's first dot *is* its last one — which is why the case that tells them apart is
    // built here rather than left to the corpus.
    const graph = syntheticGraph([node('a.b'), node('c.d'), node('e')], [], {
      edges: [
        ['a.b.out', 'c.d.in'],
        ['c.d.out', 'e.in'],
      ],
      generated: { 'a.b': ['decoder', { layer: 0n }], 'c.d': ['decoder', { layer: 1n }] },
      compositions: ['decoder'],
    });
    const answer = d6(
      graph,
      splits(),
      states({ members: ['a.b.kv', 'c.d.kv'], writer: 'a.b.kv' }),
      ['a.b', 'c.d', 'e'],
    );
    const held = (answer['graph_splits'] as readonly PyRecord[])[0] as PyRecord;
    expect(held['block']).toEqual(['a.b']);
    expect((held['separated_states'] as readonly PyRecord[])[0]?.['first']).toEqual(['a.b.kv']);
  });

  it('excludes the writer from a side it can never be on', () => {
    // `[m for m in far if m != s['writer']]` removes nothing, in either direction: `far` is the
    // side *away* from the writer, so the writer is never among its members. The filter is dead
    // code and is reproduced because it is what the tools write; this states that the two readings
    // coincide, so that a later change to either has to say which it meant.
    for (const writer of ['a.kv', 'c.kv']) {
      const held = separated(
        derived(undefined, splits(), states({ members: ['a.kv', 'b.kv', 'c.kv'], writer })),
      )[0] as PyRecord;
      const far = held['writer_side'] === 'first' ? held['second'] : held['first'];
      expect(held['history_needed_by'], writer).toEqual(far);
    }
  });

  it('restates D4’s figures without touching them, float-ness included', () => {
    // The product is built here rather than through `JSON.stringify`, because `2.0` stringifies as
    // `2` and the distinction is the point: D4 writes a `span` as `_num` answered it, and a real
    // span must stay a real in D6's bytes.
    const product: PyRecord = {
      states: [
        {
          identity: 'kv',
          evolution: 'window',
          span: value('2.0'),
          bytes_per_cached_position: value('1.5'),
          sharing: null,
          writer: 'a.kv',
          members: ['a.kv', 'b.kv'],
        },
      ],
    };
    const held = separated(derived(undefined, splits(), product))[0] as PyRecord;
    expect([held['span'], held['bytes_per_cached_position'], held['sharing']]).toEqual([
      value('2.0'),
      1.5,
      null,
    ]);
    expect(typeof held['span']).toBe('number');
  });
});
