/**
 * Where the specification states each of its identifiers — plan §1, §4.17.
 *
 * **Generated by `editor/scripts/anchors.ts` (`pnpm anchors`) from `docs/SPECIFICATION.md`. Do not
 * edit.** `tests/audit/anchors.test.ts` reads the same source and requires this file to equal
 * what the script would write, so a rule renumbered or a section re-anchored fails the audit
 * rather than shipping as a link that lands nowhere.
 *
 * The V, I, N, O series, 78 identifiers. Each carries the anchor of the section
 * that **states** it — not of the many places that cite it — and that section's heading, which is
 * what a link says it is taking the reader to.
 */

/** One identifier, and the section that states it. */
export interface SpecificationAnchor {
  /** The section's anchor, as `docs/SPECIFICATION.md` writes it and the built page carries it. */
  readonly anchor: string;
  /** The section's heading, word for word. */
  readonly section: string;
}

/** Every identifier the specification states, in the order it states them. */
export const SPECIFICATION_ANCHORS: Readonly<Record<string, SpecificationAnchor>> = {
  'V1': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V2': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V3': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V4': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V5': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V6': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V7': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V8': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V9': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V10': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V11': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V12': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V13': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V14': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V15': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V16': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V17': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V18': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V19': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'V20': { anchor: '6--static-semantics', section: '§6 — Static semantics' },
  'I1': { anchor: '91--invariants', section: '9.1 — Invariants' },
  'I2': { anchor: '91--invariants', section: '9.1 — Invariants' },
  'I3': { anchor: '91--invariants', section: '9.1 — Invariants' },
  'I4': { anchor: '91--invariants', section: '9.1 — Invariants' },
  'I5': { anchor: '91--invariants', section: '9.1 — Invariants' },
  'I6': { anchor: '91--invariants', section: '9.1 — Invariants' },
  'I7': { anchor: '91--invariants', section: '9.1 — Invariants' },
  'I8': { anchor: '91--invariants', section: '9.1 — Invariants' },
  'I9': { anchor: '91--invariants', section: '9.1 — Invariants' },
  'I11': { anchor: '91--invariants', section: '9.1 — Invariants' },
  'N1': { anchor: '92--non-requirements', section: '9.2 — Non-requirements' },
  'N2': { anchor: '92--non-requirements', section: '9.2 — Non-requirements' },
  'N3': { anchor: '92--non-requirements', section: '9.2 — Non-requirements' },
  'N4': { anchor: '92--non-requirements', section: '9.2 — Non-requirements' },
  'N5': { anchor: '92--non-requirements', section: '9.2 — Non-requirements' },
  'N6': { anchor: '92--non-requirements', section: '9.2 — Non-requirements' },
  'N7': { anchor: '92--non-requirements', section: '9.2 — Non-requirements' },
  'N8': { anchor: '92--non-requirements', section: '9.2 — Non-requirements' },
  'N9': { anchor: '92--non-requirements', section: '9.2 — Non-requirements' },
  'O0.1': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O0.2': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O0.3': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O0.4': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O0.5': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O0.6': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O1.1': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O1.2': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O1.3': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O2.1': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O2.2': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O2.3': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O3.2': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O3.3': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O3.5': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O4.1': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O4.2': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O4.3': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O4.4': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O4.5': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O5.1': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O5.2': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O5.3': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O5.4': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O5.5': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O5.7': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O5.8': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O5.10': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O6.1': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O6.2': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O6.6': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O7.1': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O8.1': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O8.2': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O8.3': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O9.1': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O9.2': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O9.4': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
  'O9.5': { anchor: 'appendix-a--requirements', section: 'Appendix A — Requirements' },
};
