/**
 * The documentation site's navigation, vendored — component inventory §2, artboard S18.
 *
 * **Generated by `editor/scripts/site-nav.ts` (`pnpm site-nav`) from `docs/style/nav.html`. Do not
 * edit.** `tests/audit/site-bar.test.ts` reads the same source and requires this file to equal
 * it, so a guide added to the site appears in the editor's bar rather than being missing from it.
 *
 * Every href is stated below the site root, as `nav.html` states it with its `%ROOT%`
 * placeholder: the editor resolves them against the directory above its own page, which is where
 * the site is (D11, and `documentationBase()` for the Help menu's links).
 */

/** One entry of the site's navigation. */
export interface SiteEntry {
  /** Where the page is, below the site root. */
  readonly href: string;
  /** What the site calls it. */
  readonly label: string;
}

/** One group of entries, as the site arranges them. */
export interface SiteGroup {
  /** The container's class in `nav.html`, without its `nav-` prefix. */
  readonly name: string;
  /** The `<summary>` the site folds the group behind, or `null` for the entries it shows. */
  readonly label: string | null;
  readonly entries: readonly SiteEntry[];
}

/** Where the lockup points: the site's own front page. */
export const SITE_HOME = 'index.html';

/** The site's entries, in the order `nav.html` writes them. */
export const SITE_NAV: readonly SiteGroup[] = [
  {
    name: 'main',
    label: null,
    entries: [
      { href: 'index.html', label: 'Overview' },
      { href: 'models/index.html', label: 'Models' },
      { href: 'spec/architecture.html', label: 'Architecture' },
      { href: 'spec/glossary.html', label: 'Glossary' },
    ],
  },
  {
    name: 'guides',
    label: 'Guides',
    entries: [
      { href: 'spec/specification.html', label: 'Specification' },
      { href: 'spec/tensorspine-model_json.html', label: 'Model guide' },
      { href: 'spec/tensorspine-primitive-library-unit.html', label: 'Primitive Library-unit guide' },
      { href: 'spec/tensorspine-derived_json.html', label: 'Derived guide' },
      { href: 'spec/harness.html', label: 'Harness guide' },
      { href: 'spec/primitive-library-documentation.html', label: 'Primitive Library guide' },
      { href: 'spec/tensorspine-fixture.html', label: 'Fixture guide' },
    ],
  },
  {
    name: 'reports',
    label: 'Generated',
    entries: [
      { href: 'primitive-library/index.html', label: 'Primitives' },
      { href: 'status/index.html', label: 'Status' },
      { href: 'branch-ledger/index.html', label: 'Branch ledger' },
    ],
  },
];
