#!/usr/bin/env sh
# Render the generated primitive library Markdown as a styled HTML page.
#   docs/style/primitive-library.sh IN.md [OUT.html] [NAV.html]
# NAV.html is the site navigation for this page (tools/site.sh resolves
# nav.html for it); without it the page keeps the name and drops both the
# monogram and the links, which would lead nowhere outside the site.
# The site build supplies temporary Markdown generated by --document primitive-library.
set -eu
here=$(cd "$(dirname "$0")" && pwd)
if [ "$#" -lt 1 ]; then
  echo "usage: docs/style/primitive-library.sh IN.md [OUT.html] [NAV.html]" >&2
  exit 2
fi
in=$1
out=${2:-"${in%.md}.html"}
nav=${3:-}
css=$(python3 -c "import os,sys;print(os.path.relpath(sys.argv[1],sys.argv[2]))" "$here/primitive-library.css" "$(dirname "$out")")

if [ -z "$nav" ]; then
  nav=$(mktemp)
  trap 'rm -f "$nav"' EXIT
  cat > "$nav" <<'BAR'
<nav class="sitebar">
  <span class="wordmark"><span class="name"><span>Tensor</span><span>Spine</span></span></span>
  <span class="sitekind">Reference primitive library</span>
</nav>
BAR
fi
pandoc "$in" \
  --from markdown \
  --to html5 \
  --standalone \
  --section-divs \
  --toc --toc-depth=4 \
  --template "$here/primitive-library.html" \
  --lua-filter "$here/primitive-library.lua" \
  --css "$css" \
  --include-before-body "$nav" \
  --metadata pagetitle="TensorSpine reference primitive library" \
  --output "$out"
echo "wrote $out"
