/**
 * Vendor the wordmark's monogram — plan §4.21, component inventory §1.
 *
 * > The logo is the monogram of `docs/tensorspine.svg` arranged as `docs/style/nav.html` does —
 * > placed and scaled, never redrawn.
 *
 * So this script copies, and copies exactly: it lifts the one `<svg class="mono" …>…</svg>`
 * element out of the documentation site's navigation and writes it into
 * `packages/ui/src/shell/logo.ts` as a string the bar inlines. Nothing is reformatted, nothing is
 * minified, no `id` is renamed and no gradient is touched — `nav.html` already did the only work
 * there was to do (Inkscape's editor attributes dropped, the ids prefixed `ts-` so a page cannot
 * collide with them, and the plain SVG2 `href` written beside every `xlink:href`, without which a
 * gradient that inherits its stops disappears wherever the namespaced form is stripped).
 *
 * The editor cannot link to the site's copy: it is a page that must run from a folder of its own,
 * beside the site and not inside it (D11). Inlining is what `nav.html` does for the same reason,
 * and `tests/audit/logo.test.ts` holds the copy to the source so it cannot drift.
 *
 * Run it with `pnpm logo`, from `editor/`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/** `editor/`, this script's own workspace. */
export const editorRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** The repository the editor is part of (D14): the site's navigation is read from it. */
export const repositoryRoot = resolve(editorRoot, '..');

/** Where the arrangement lives: the documentation site's one navigation source. */
export const NAV = 'docs/style/nav.html';

/** Where the copy lives. */
export const MODULE = 'packages/ui/src/shell/logo.ts';

/**
 * The monogram, as `nav.html` carries it.
 *
 * One element, matched by its opening tag and its last close: the file holds exactly one `<svg>`,
 * and the extraction refuses rather than guesses if that ever stops being true.
 */
export function monogramOf(nav: string): string {
  const opening = nav.indexOf('<svg class="mono"');
  const closing = nav.indexOf('</svg>');
  if (opening < 0 || closing < opening) {
    throw new Error(`${NAV}: no <svg class="mono"> element to vendor`);
  }
  if (nav.indexOf('<svg', opening + 1) >= 0 || nav.indexOf('</svg>', closing + 1) >= 0) {
    throw new Error(`${NAV}: more than one <svg> element, so which one is the monogram is a guess`);
  }
  return nav.slice(opening, closing + '</svg>'.length);
}

/** The module written beside the bar. */
export function moduleFor(monogram: string): string {
  if (monogram.includes('`') || monogram.includes('${')) {
    throw new Error('the monogram cannot be written as a template literal without escaping it');
  }
  return `/**
 * The wordmark's monogram, vendored — plan §4.21, component inventory §1.
 *
 * **Generated by \`editor/scripts/logo.ts\` (\`pnpm logo\`) from \`${NAV}\`. Do not edit.**
 * \`tests/audit/logo.test.ts\` reads the same source and requires this file to equal it, so a
 * drawing that drifted from the site's would fail the audit rather than ship.
 *
 * It is the drawing of \`docs/tensorspine.svg\` placed and scaled and nothing else: the
 * \`viewBox\` crops the sheet to the mark, the gradients keep the file's own ramp, and the name
 * beside it is HTML text in the bar (\`--logo-a\` and \`--logo-b\`), never a redrawing of the
 * file's own lettering.
 */

/** The monogram as \`docs/style/nav.html\` arranges it, inlined by the bar. */
export const MONOGRAM = \`${monogram}\`;
`;
}

export function vendorLogo(): { bytes: number } {
  const nav = readFileSync(join(repositoryRoot, NAV), 'utf8');
  const text = moduleFor(monogramOf(nav));
  writeFileSync(join(editorRoot, MODULE), text);
  return { bytes: text.length };
}

const invoked = process.argv[1];
if (invoked !== undefined && resolve(invoked) === fileURLToPath(import.meta.url)) {
  const { bytes } = vendorLogo();
  process.stdout.write(`${MODULE}  ${(bytes / 1024).toFixed(1)} KiB\n`);
}
