/**
 * One identity as the editor **edits** it — plan §4.14, artboard S8.
 *
 * > **Parameter and state identities** are created from slot chips or the Identities list: name (a
 * > `symbol_instance` with indices), members, dtype, location. … **Locations** (parameter
 * > identities): a chooser over the four forms — from the `location` `oneOf` — each rendered from
 * > its schema … `stack`: axis (select of the slot's axis names plus `multiplicity` when the slot
 * > declares one — **names the core returns**), part (a nested location).
 *
 * Three questions a location editor asks, and none of them is a component's to answer:
 *
 * | Question | Answered by |
 * |---|---|
 * | which axes a `stack`, a `concat` or a `slice` may name | the slot's shape **as stored** ({@link storageShape}), which is what `evaluate_location` resolves an axis against |
 * | what an `{index}` and a `{coordinate}` token may name | the index environment the rule fires in, and the same stored axes |
 * | what the names evaluate to, instance by instance | `evaluate_location`'s own answer, which the bindings stage already computed and D3 writes |
 *
 * **The preview is D3's own value, one step before D3.** §4.14 asks for "the evaluated names for
 * the current preview index … from D3 when fresh, else from the core's evaluation"; the two are
 * one value — `TensorInstance.location` is `evaluate_location`'s answer, D3 copies it into the
 * derived document, and V17 checks it — so the preview reads the analysis rather than the
 * derivation. It is the fresher of the two (the analysis is recomputed on every keystroke, a
 * derivation follows a passing validation) and it is never a second evaluator.
 *
 * **What is not here.** The refusals: V17's lines are `analyse`'s and land in Problems with their
 * pointers (§4.17), and a location editor that restated them would be a second implementation of
 * a rule. And the verdict on a candidate — a tensor dragged from the Weights panel, a slot joining
 * an identity — which is {@link checkCandidate}'s, on that one candidate.
 */
import type { Env } from '../expr/model.js';
import { toPython, type PyValue } from '../expr/value.js';
import { jsonObject, type JsonObject, type JsonValue } from '../json/index.js';
import { demand, entries, optional } from '../library/access.js';
import type { Library } from '../library/index.js';
import { pyStr } from '../library/repr.js';
import {
  keyOf,
  locationNames,
  present,
  storageShape,
  whereOfSite,
  type Analysis,
  type IdentityMember,
  type ResolvedSite,
  type SiteKey,
  type StateInstance,
  type TensorInstance,
} from '../validate/index.js';

import { literalIndex } from './folded.js';
import { describeShape, type DescribedShape } from './shape.js';

/** Which identity the editor is asking about: the rule that declares it, and which map it is in. */
export interface IdentityRequest {
  /** The rule as the **normalised** document names it: `embed.weight`, `decoder.attn.q`. */
  readonly rule: string;
  /** Whether it is a state identity (D4) rather than a parameter one (D3). */
  readonly state: boolean;
}

/** One member of the identity, as the sheet's rows and the location's slot need it. */
export interface IdentityMemberFacts {
  /** How a refusal and D1 name the site: `embed`, `decoder/attn[layer=0]`. */
  readonly where: string;
  /** The site itself, so a gesture can write an endpoint for it without reading it back. */
  readonly site: SiteKey;
  /** The parameter slot or the state port the member names. */
  readonly slot: string;
  /**
   * Its position in the rule's written member list, or `null` where it came from none.
   *
   * What a gesture removes when a slot leaves the identity: the item at this place. The interface
   * cannot find it — an endpoint is a selector and reading one back is the core's business — so
   * the position travels with the member.
   */
  readonly at: number | null;
  /** The precision roles it carries: a slot's own, or every payload component's of a state port. */
  readonly roles: readonly string[];
  /** Whether the slot or the port is present under its instance's arguments (V7's own skip). */
  readonly present: boolean;
}

/** What a token of a physical name may name, by the member the schema writes it under. */
export interface TokenNames {
  /** The member: the item form's own discriminating key, as the grammar declares it. */
  readonly member: string;
  /** The names offered there, in the order the document or the declaration writes them. */
  readonly names: readonly string[];
  /**
   * Whether the **document declares** those names, or the location itself generates them.
   *
   * A composition index is declared — the rule fires once per point of its grid — and a `stack`'s
   * coordinate is not: it is generated by the stack, one per coordinate of the axis it names.
   * The distinction is the *meaning* of the two token forms, which is why it is answered here and
   * not read off the member's name in a component (§1: the interface names no word of the
   * grammar).
   */
  readonly declared: boolean;
}

/** One region a location slices, as the preview prints it. */
export interface SlicedName {
  readonly tensor: string;
  readonly offset: string;
  readonly extent: string;
  /**
   * Where the region ends — `offset + extent`, which is what S8's `[1152 : 2304]` prints.
   *
   * Answered here rather than added in the interface: the two are the evaluated location's own
   * integers and a component that added them would be computing a figure (inventory §7).
   */
  readonly end: string;
}

/** One identity instance of the rule: what D3 and D4 name their rows after (§4.11's Derived). */
export interface IdentityInstance {
  /** `decoder.attn.q[layer=0]`, `tied_embeddings` — the name the products carry. */
  readonly identity: string;
  /** The index environment the rule fired in, in the order the environment binds it. */
  readonly indices: readonly { readonly name: string; readonly value: string }[];
  /** The physical names the location binds whole, evaluated — S8's own preview lines. */
  readonly names: readonly string[];
  /** The regions it slices, evaluated. */
  readonly slices: readonly SlicedName[];
  /** Whether the location evaluated at all: `false` where the rule writes none, or V17 refused it. */
  readonly located: boolean;
}

/** Everything the editor asks about one identity (§4.14). */
export interface IdentityFacts {
  readonly rule: string;
  readonly state: boolean;
  /**
   * Its members, in the order the binding writes them, at the first environment the rule fired in.
   *
   * A member whose site did not resolve is out — `analyse` leaves it out of the instance for the
   * same reason, and its V1 line is in Problems.
   */
  readonly members: readonly IdentityMemberFacts[];
  /**
   * The dtypes every member's role admits — V14's own set, intersected over the roles.
   *
   * "A dtype selected for an identity is admissible for the role of every member" (V14): the set
   * a select may offer without the validator refusing it. Empty where no member's role is
   * declared by a gathered base, which is an answer and not a limit — the *select* is the
   * schema's enumeration either way (Q5: a gesture is never refused for a semantic reason, and
   * V14's line lands in Problems).
   */
  readonly dtypes: readonly string[];
  /**
   * The stored shape a location is written against: the **first resolved member's** slot.
   *
   * "One identity, one stored shape (V15 is what makes the others equal to it)" — the rule
   * `checkParameters` writes a location against, made available to the editor that writes one.
   * `null` for a state identity and where no member resolved.
   */
  readonly shape: DescribedShape | null;
  /** The axis names of that shape, in order, each once: a declared multiplicity leads (§3.4). */
  readonly axes: readonly string[];
  /** What a physical name's token forms may name, by the member each is written under. */
  readonly tokens: readonly TokenNames[];
  /** One entry per identity instance the rule produced, in the order the bindings emitted them. */
  readonly instances: readonly IdentityInstance[];
}

/**
 * `identityFacts(analysis, library, {rule, state})`: what the sheet of one identity shows.
 *
 * `null` where the document's bindings produced no instance of that rule at all — a rule whose
 * every site a guard removed (§5.2 rule 3), or a name no binding carries.
 */
export function identityFacts(
  analysis: Analysis,
  library: Library,
  request: IdentityRequest,
): IdentityFacts | null {
  const instances = request.state
    ? analysis.bindings.stateInstances.filter((one) => one.rule === request.rule)
    : analysis.bindings.tensorInstances.filter((one) => one.rule === request.rule);
  if (instances.length === 0) return null;
  const members = memberFacts(analysis, instances, request.state);
  const target = request.state ? null : locationTarget(analysis, instances as TensorInstance[]);
  const shape = target === null ? null : describeShape(storageShape(target.slot), target.site.args);
  // The **local** names, which is what a location's `axis` is matched against: `evaluate_location`
  // reads `axes = [a['name'] for a in shape['axes']]` and answers "'x' is not an axis of the slot
  // (axes: …)" over those. A declared multiplicity leads them, named `multiplicity` (§3.4).
  const axes = shape === null ? [] : distinct(shape.map((axis) => pyStr(axis.name)));
  return {
    rule: request.rule,
    state: request.state,
    members,
    dtypes: admissibleDtypes(library, members),
    shape,
    axes,
    tokens: request.state ? [] : tokenNames(instances, axes),
    instances: instances.map((one) => instanceFacts(one)),
  };
}

/**
 * Where a binding rule's location names an **axis of the slot's stored shape**, as pointers.
 *
 * RFC 6901 pointers relative to the rule — `/location/stack/axis`,
 * `/location/concat/parts/1/slice/axis` — so that §4.14's axis select ("names the core returns")
 * is filled at the rows that take one and nowhere else. The interface may not find them itself:
 * `axis` **is** an enumerated value of the four schemas and `stack`, `concat` and `slice` are the
 * grammar's own tags, which §1 (b) forbids it to write; and a location recurses, so no fixed list
 * of places would do either.
 *
 * It reads the **tree**, not the analysis, and that is the point: a location is edited through
 * states the grammar refuses — a `stack` whose axis is still blank — and the places are exactly
 * what the author needs then. The names those places offer are the slot's, which {@link
 * IdentityFacts.axes} answers from the last analysis there was.
 */
export function locationAxisPlaces(rule: JsonValue): string[] {
  return axisPlaces(optional(toPython(rule), LOCATION, null));
}

/**
 * Where an axis of the stored shape is named inside a location, as pointers into the rule.
 *
 * The walk is the grammar's own recursion — a `stack` has one part, a `concat` has several, a
 * `slice` names an axis and no location under it.
 */
function axisPlaces(location: PyValue): string[] {
  const found: string[] = [];
  const walk = (at: string, held: PyValue): void => {
    if (held === null || typeof held !== 'object' || Array.isArray(held)) return;
    const stack = optional(held, STACK, null);
    if (stack !== null) {
      found.push(`${at}/${STACK}/${AXIS}`);
      walk(`${at}/${STACK}/${PART}`, optional(stack, PART, null));
      return;
    }
    const concat = optional(held, CONCAT, null);
    if (concat !== null) {
      found.push(`${at}/${CONCAT}/${AXIS}`);
      const parts = optional(concat, PARTS, null);
      if (Array.isArray(parts)) {
        (parts as readonly PyValue[]).forEach((part, index) => {
          walk(`${at}/${CONCAT}/${PARTS}/${String(index)}`, part);
        });
      }
      return;
    }
    if (optional(held, SLICE, null) !== null) found.push(`${at}/${SLICE}/${AXIS}`);
  };
  walk(`/${LOCATION}`, location);
  return found;
}

/** The member the location is written against: "the first resolved member's slot" (V17). */
function locationTarget(
  analysis: Analysis,
  instances: readonly TensorInstance[],
): { readonly site: ResolvedSite; readonly slot: PyValue } | null {
  for (const instance of instances) {
    for (const member of instance.members) {
      const site = analysis.resolved.get(keyOf(member.site));
      if (site === undefined) continue;
      const slot = optional(demand(site.definition, 'parameters'), pyStr(member.name), null);
      if (slot === null) continue;
      return { site, slot };
    }
  }
  return null;
}

/**
 * The members of the rule, resolved at the **first** index environment it fired in.
 *
 * A rule's members are written once — `[{"site": "attn", "parameter": "q"}]` — and an instance is
 * that list selected at one point of the grid, so one instance *is* the rule's member list, with
 * the site each member names at the representative iteration (§4.8, the card's own reading).
 * Taking them over every instance would answer thirty-two members for a rule that declares one.
 */
function memberFacts(
  analysis: Analysis,
  instances: readonly (TensorInstance | StateInstance)[],
  state: boolean,
): IdentityMemberFacts[] {
  const found: IdentityMemberFacts[] = [];
  for (const member of instances[0]?.members ?? []) {
    const site = analysis.resolved.get(keyOf(member.site));
    if (site === undefined) continue;
    found.push(memberOf(site, member, state));
  }
  return found;
}

/** One member: the roles V14 reads of it, and whether V7 skips it. */
function memberOf(site: ResolvedSite, member: IdentityMember, state: boolean): IdentityMemberFacts {
  const declared = optional(
    demand(site.definition, state ? 'state_ports' : 'parameters'),
    pyStr(member.name),
    null,
  );
  return {
    where: whereOfSite(site.key),
    site: site.key,
    slot: pyStr(member.name),
    at: member.at ?? null,
    roles: declared === null ? [] : rolesOf(declared, state),
    present: declared !== null && present(declared, site.args),
  };
}

/**
 * The precision roles V14 compares a dtype against: a slot's own, a state port's whole payload.
 *
 * `check_parameters` reads `slot['role']`; `check_states` walks `port['payload']` and reads each
 * component's. Both are here so that the set a select shows is the set the refusal is written
 * against.
 */
function rolesOf(declared: PyValue, state: boolean): string[] {
  if (!state) return [pyStr(demand(declared, 'role'))];
  return entries(demand(declared, 'payload')).map(([, component]) =>
    pyStr(demand(component, 'role')),
  );
}

/** The dtypes admissible for **every** role the members carry, in the policy's own order. */
function admissibleDtypes(
  library: Library,
  members: readonly IdentityMemberFacts[],
): readonly string[] {
  let admitted: string[] | null = null;
  for (const member of members) {
    for (const role of member.roles) {
      const declared = library.precision.get(role);
      if (declared === undefined) continue;
      const values = listOfNames(optional(declared, 'admissible', []));
      admitted = admitted === null ? values : admitted.filter((one) => values.includes(one));
    }
  }
  return admitted ?? [];
}

/** A declared list of dtype names, as the policy writes them. */
function listOfNames(value: PyValue): string[] {
  return Array.isArray(value) ? (value as readonly PyValue[]).map((one) => pyStr(one)) : [];
}

/**
 * What each token form may name: the indices the rule fires under, and the stored shape's axes.
 *
 * The members are the grammar's own — the item forms of `physical_name` — and the `declared` flag
 * is what tells the two apart for a reader: an index is a declaration of the document, a
 * coordinate is generated by the `stack` that encloses the name.
 */
function tokenNames(
  instances: readonly (TensorInstance | StateInstance)[],
  axes: readonly string[],
): TokenNames[] {
  const first = instances[0];
  const env: Env = first !== undefined && 'env' in first ? first.env : new Map<string, PyValue>();
  return [
    { member: INDEX, names: [...env.keys()], declared: true },
    { member: COORDINATE, names: [...axes], declared: false },
  ];
}

/** One instance: its indices, and the names its location evaluated to. */
function instanceFacts(instance: TensorInstance | StateInstance): IdentityInstance {
  const env: Env = 'env' in instance ? instance.env : new Map<string, PyValue>();
  const evaluated = 'location' in instance ? instance.location : undefined;
  const used = evaluated === undefined ? null : locationNames(evaluated);
  return {
    identity: instance.identity,
    indices: [...env].map(([name, value]) => ({ name, value: pyStr(value) })),
    names: used === null ? [] : [...used.whole],
    slices:
      used === null
        ? []
        : used.slices.map((one) => ({
            tensor: one.name,
            offset: one.offset.toString(),
            extent: one.extent.toString(),
            end: (one.offset + one.extent).toString(),
          })),
    located: used !== null,
  };
}

/** The names of a list, each once, in the order they first appear. */
function distinct(names: readonly string[]): string[] {
  return [...new Set(names)];
}

/**
 * The member endpoint a gesture writes — the inverse of the member loop of `check_parameters`.
 *
 * §4.7's chip-onto-chip gesture and §4.11's "Bind privately" / "Tie to…" build one, and the
 * interface may not: what a `parameter_endpoint` looks like is the schema's, and the core is where
 * the grammar's words live (feature 2.9's rule for `value_endpoint`, one binding along).
 *
 * The form follows the **place the rule is written in**: a rule scoped to the composition the site
 * belongs to names the site alone — "each rule is the top-level rule `<composition>.<rule>` whose
 * site endpoints select the generated instance at the current indices" (§5.2) — and every other
 * rule names it with a selector, whose indices are the concrete point the chip stands for.
 */
export function identityMember(
  site: SiteKey,
  slot: string,
  options: { readonly state: boolean; readonly scope?: string },
): JsonObject {
  const member = options.state ? STATE : PARAMETER;
  const scope = options.scope ?? '';
  if (site.kind === 'gen' && scope === site.composition) {
    return jsonObject([
      { name: SITE, value: site.name },
      { name: member, value: slot },
    ]);
  }
  if (site.kind === 'gen') {
    return jsonObject([
      {
        name: INSTANCE,
        value: jsonObject([
          { name: KIND, value: GENERATED },
          { name: COMPOSITION, value: site.composition },
          { name: INSTANCE, value: site.name },
          {
            name: INDICES,
            value: jsonObject(
              site.indices.map((one) => ({ name: one.name, value: literalIndex(wholeOf(one.value)) })),
            ),
          },
        ]),
      },
      { name: member, value: slot },
    ]);
  }
  return jsonObject([
    {
      name: INSTANCE,
      value: jsonObject([
        { name: KIND, value: ROOT },
        { name: INSTANCE, value: site.name },
      ]),
    },
    { name: member, value: slot },
  ]);
}

/**
 * An index value as the selector writes it: the whole number the expansion bound it to.
 *
 * A composition's indices are integers — `index_ranges` are expressions over cardinalities and
 * `range` walks them — so the endpoint a chip writes carries that integer as a literal, which is
 * what `decoder.entry` writes for the first layer. Anything else would be a value the grid never
 * produced, and `0` is the conservative reading of one.
 */
function wholeOf(value: PyValue): bigint {
  if (typeof value === 'bigint') return value;
  if (typeof value === 'number' && Number.isInteger(value)) return BigInt(value);
  return 0n;
}

/**
 * What the tokens of an instance's `weights_location_prefix` may name (§3.4, §4.14).
 *
 * The same three item forms, read at the one other place the grammar writes a physical name: an
 * instance's prefix, which `analyse` evaluates in the site's own index environment before the
 * slots are bound (feature 1.6b's reason for lifting `_physical_name` out). So an `{index}` may
 * name an index the site sits under, and a `{coordinate}` names nothing at all — there is no
 * `stack` over an axis here to generate one, which is a fact and not an omission.
 */
export function prefixTokens(site: SiteKey): TokenNames[] {
  return [
    { member: INDEX, names: site.indices.map((one) => one.name), declared: true },
    { member: COORDINATE, names: [], declared: false },
  ];
}

/**
 * The symbol a new identity declares: `{"name": …}`, the `symbol_instance` a rule writes.
 *
 * A scoped rule may leave it out — §5.2 rule 7 names the identity `<composition>.<rule>` — and a
 * top-level rule requires it, so the caller says which it is writing and this answers the member.
 */
export function identitySymbol(name: string): JsonObject {
  return jsonObject([{ name: NAME, value: name }]);
}

/** The member of a parameter binding that names its identity. */
export const TENSOR_SYMBOL = 'tensor';
/** The member of a state binding that names its identity. */
export const STATE_SYMBOL = 'identity';
/** The member of a binding that lists what shares the identity. */
export const MEMBERS = 'members';
/** The member a location is written under. */
export const LOCATION = 'location';
/** The map of `bindings` a parameter identity is written in. */
export const PARAMETER_BINDINGS = 'parameters';
/** The map of `bindings` a state identity is written in. */
export const STATE_BINDINGS = 'states';

const PARAMETER = 'parameter';
const STATE = 'state';
const SITE = 'site';
const INSTANCE = 'instance';
const COMPOSITION = 'composition';
const INDICES = 'indices';
const KIND = 'kind';
const ROOT = 'root';
const GENERATED = 'generated';
const NAME = 'name';
const INDEX = 'index';
const COORDINATE = 'coordinate';
const STACK = 'stack';
const CONCAT = 'concat';
const SLICE = 'slice';
const PART = 'part';
const PARTS = 'parts';
const AXIS = 'axis';
