import { describe, expect, it } from 'vitest';

import { identityFacts, serialize, type JsonValue } from '@tensorspine/lang';
import { nodeAt, type Path } from '@tensorspine/store';

import { locationPreview } from '../../src/sheet/location.js';
import {
  tokenModel,
  withForm,
  withText,
  withToken,
  withoutToken,
} from '../../src/sheet/tokens.js';
import { shapeAt } from '../../src/sheet/places.js';
import { analysisOf, context, library, tree } from './source.js';

/**
 * The physical-name token editor's model — §4.14, artboard S8.
 *
 * What is under test is that the three item forms, the names each may carry and the value an edit
 * writes all come from somewhere else: the forms from the walker over `physical_name`'s own
 * `oneOf`, the names from the core (`identityFacts`), and the written value from the form the
 * chooser answered. The documents are the corpus's own.
 */

/** The shape and the value of one place of a corpus document. */
function at(name: string, path: Path): { shape: ReturnType<typeof shapeAt>; value: JsonValue | undefined } {
  return {
    shape: shapeAt(context.shapes, path, 'model'),
    value: nodeAt(tree(name), path),
  };
}

const ATTN_Q = ['compositions', 'decoder', 'bindings', 'parameters', 'attn.q', 'location', 'tensor'] as Path;

describe('the tokens of a physical name', () => {
  it('reads llama3-8b’s `decoder.attn.q` as a literal, an index and a literal', () => {
    const place = at('llama3-8b', ATTN_Q);
    const facts = identityFacts(analysisOf('llama3-8b'), library(), {
      rule: 'decoder.attn.q',
      state: false,
    });
    const model = tokenModel(context, place.shape, place.value, facts?.tokens ?? []);

    expect(model.tokens.map((one) => one.form)).toEqual(['string', 'index', 'string']);
    expect(model.tokens.map((one) => one.text)).toEqual([
      'model.layers.',
      'layer',
      '.self_attn.q_proj.weight',
    ]);
    // The colour of a chip is a fact of the core's, never the member's name: an index is declared
    // by the document, a coordinate is generated by the stack, a literal is neither.
    expect(model.tokens.map((one) => one.declared)).toEqual([null, true, null]);
    expect(model.tokens[1]?.names).toEqual(['layer']);
    // `minItems: 1` — the schema's, which is what stops the last token being removed.
    expect(model.least).toBe(1);
  });

  it('offers the three item forms of the grammar, with the names the core gives each', () => {
    const place = at('gemma3n-kvshare', ['bindings', 'parameters', 'expand.projection', 'location', 'stack', 'part', 'tensor'] as Path);
    const facts = identityFacts(analysisOf('gemma3n-kvshare'), library(), {
      rule: 'expand.projection',
      state: false,
    });
    const model = tokenModel(context, place.shape, place.value, facts?.tokens ?? []);

    expect(model.forms.map((one) => one.tag)).toEqual(['string', 'index', 'coordinate']);
    expect(model.forms.map((one) => one.member)).toEqual([null, 'index', 'coordinate']);
    // The coordinate form offers the slot's own stored axes — `multiplicity` among them.
    expect(model.forms[2]?.names).toEqual(['multiplicity', 'feature']);
    expect(model.forms[2]?.declared).toBe(false);
    expect(model.tokens.map((one) => one.form)).toEqual(['string', 'coordinate', 'string']);
    expect(model.tokens[1]?.text).toBe('multiplicity');
  });
});

describe('what an edit writes', () => {
  it('changes a literal, and keeps the rest of the name as it was', () => {
    const place = at('llama3-8b', ATTN_Q);
    const model = tokenModel(context, place.shape, place.value);
    const written = withText(model, place.value, 0, 'model.decoder.layers.');
    expect(serialize(written)).toBe(
      [
        '[',
        '  "model.decoder.layers.",',
        '  {',
        '    "index": "layer"',
        '  },',
        '  ".self_attn.q_proj.weight"',
        ']',
        '',
      ].join('\n'),
    );
  });

  it('puts a token into another form, carrying its text — the chooser’s own blank', () => {
    const place = at('llama3-8b', ATTN_Q);
    const model = tokenModel(context, place.shape, place.value);
    // The index becomes a literal of the same text, and back again: the form is the schema's, the
    // text is the author's, and neither is invented here.
    const literal = withForm(model, place.value, 1, 'string');
    expect(serialize(literal)).toContain('"layer",');
    const back = tokenModel(context, place.shape, literal);
    expect(serialize(withForm(back, literal, 1, 'coordinate'))).toContain('"coordinate": "layer"');
  });

  it('adds an empty literal at the end and removes a token by its place', () => {
    const place = at('llama3-8b', ATTN_Q);
    const model = tokenModel(context, place.shape, place.value);
    const added = withToken(model, place.value);
    expect(Array.isArray(added) ? added.length : 0).toBe(4);
    // The empty literal matches **no** alternative — `minLength: 1` is the schema's — so the
    // chooser answers none and Ajv's row is what says so, which is D5's arrangement and feature
    // 2.12's `Add input` precedent. Typing into the chip writes it as the first form.
    expect(tokenModel(context, place.shape, added).tokens[3]).toMatchObject({ form: '', text: '' });
    const typed = withText(tokenModel(context, place.shape, added), added, 3, '.bias');
    expect(serialize(typed)).toContain('".bias"');
    const removed = withoutToken(place.value, 1);
    expect(serialize(removed)).toBe(
      '[\n  "model.layers.",\n  ".self_attn.q_proj.weight"\n]\n',
    );
  });

  it('reads a place the document has not written yet as no tokens at all', () => {
    const place = at('llama3-8b', ['instances', 'embed', 'weights_location_prefix'] as Path);
    const model = tokenModel(context, place.shape, place.value);
    expect(model.tokens).toEqual([]);
    expect(model.forms.map((one) => one.tag)).toEqual(['string', 'index', 'coordinate']);
    expect(serialize(withToken(model, place.value))).toBe('[\n  ""\n]\n');
  });
});

describe('the evaluated preview beneath a location (S8)', () => {
  it('draws the head, what is not drawn, and the last — S8’s own four lines', () => {
    const facts = identityFacts(analysisOf('llama3-8b'), library(), {
      rule: 'decoder.attn.q',
      state: false,
    });
    const preview = locationPreview(facts);
    expect(preview.instances).toBe(32);
    expect(preview.located).toBe(32);
    // Two, then the last, with the count of what stands between them: `… 29 more`.
    expect(preview.lines.map((line) => line.indices)).toEqual([
      'layer = 0',
      'layer = 1',
      'layer = 31',
    ]);
    expect(preview.more).toBe(29);
    expect(preview.lines[2]?.names).toEqual(['model.layers.31.self_attn.q_proj.weight']);
  });

  it('draws the regions a slice names, offset and end, as S8 writes them', () => {
    const sliced = locationPreview(
      identityFacts(analysisOf('qwen3.5-35b-a3b'), library(), {
        rule: 'vision.attn.k',
        state: false,
      }),
    );
    // Twenty-seven vision layers: the head, the last, and the twenty-four between them.
    expect(sliced.instances).toBe(27);
    expect(sliced.more).toBe(24);
    expect(sliced.lines[0]?.slices[0]).toContain('[1152 : 2304]');
    expect(sliced.lines[0]?.names).toEqual([]);
  });

  it('draws every instance where there are few', () => {
    const one = locationPreview(
      identityFacts(analysisOf('llama3-8b'), library(), { rule: 'embed.weight', state: false }),
    );
    expect(one.instances).toBe(1);
    expect(one.more).toBe(0);
    expect(one.lines[0]?.indices).toBe('');
    expect(one.lines[0]?.names).toEqual(['model.embed_tokens.weight']);
  });

  it('answers nothing at all for an identity the core could not describe', () => {
    expect(locationPreview(null)).toEqual({ lines: [], more: 0, instances: 0, located: 0 });
  });
});
