import AxeBuilder from '@axe-core/playwright';
import { expect, test, type Page } from '@playwright/test';

import { platformUrl, publishedOrigin } from '../playwright.config.js';
import { BASE, CORRUPT, CORRUPTED, MODEL, NO_CORS, WORKSPACE } from './remote-server.js';

/**
 * Feature 2.20 — a base and a workspace opened from an **address**, in a real browser.
 *
 * The fixture server of `remote-server.ts` is a second origin (a second port is a second origin to
 * a browser), and every set it serves was generated by `pnpm manifest` — never written by hand.
 * What is asked here is exactly what the feature's block asks for, and each of them needs an
 * engine to be worth anything:
 *
 *   - **a base served with its manifest is gathered**, and a model instantiating one of its units
 *     validates and derives. The published workspace's own model declares a base the set does not
 *     hold, so the change is visible: the loader's V1 before, no problems and six products after;
 *   - **a file whose sha256 disagrees is refused naming the path**, and nothing of the set opens;
 *   - **a host that sends no CORS header is refused naming the header**, rather than spinning;
 *   - **the address survives a reload**, for the workspace and for the base standing in it;
 *   - **offline**: a host that answers nothing opens the cache *with its age shown*, and never
 *     silently stale.
 *
 * What is *not* here: the Library palette's own section and its badge, which are feature 3.1's
 * (the activity does not exist yet); and an owned base beside a fetched one, which is 3.2's.
 */

const WORKSPACE_URL = `${publishedOrigin}/${WORKSPACE}/`;
const BASE_URL = `${publishedOrigin}/${BASE}/`;

/** Open the application and wait for it to have decided what to open (D11's own startup). */
async function open(page: Page): Promise<void> {
  await page.goto('/');
  await expect(page.locator('#root')).toHaveAttribute('data-state', 'ready');
  await expect(page.locator('#root')).toHaveAttribute('data-documents', 'ready');
}

/** Run a command of §4.4 by its menu entry, which is the way a person reaches it. */
async function command(page: Page, menu: string, id: string): Promise<void> {
  await page.locator(`nav.menu > div > button:text-is("${menu}")`).click();
  await page.locator(`.menu-pop button[data-command="${id}"]`).click();
}

/** File ▸ Open Workspace from URL…, answered with an address. */
async function openWorkspace(page: Page, address: string): Promise<void> {
  await command(page, 'File', 'file.open-workspace-url');
  await page.locator('.dlg [data-remote-address="workspace"]').fill(address);
  await page.locator('.dlg [data-open-remote="workspace"]').click();
}

/**
 * File ▸ Open Base from URL…, answered with an address and — unless one is given — the path the
 * dialog proposes, which is the set's own name.
 */
async function openBase(page: Page, address: string, at?: string): Promise<void> {
  await command(page, 'File', 'file.open-base-url');
  await page.locator('.dlg [data-remote-address="library"]').fill(address);
  if (at !== undefined) await page.locator('.dlg [data-remote-path="library"]').fill(at);
  await page.locator('.dlg [data-open-remote="library"]').click();
}

/** Open one document of the workspace through File ▸ Open Model…. */
async function openDocument(page: Page, path: string): Promise<void> {
  await command(page, 'File', 'file.open-model');
  await page.locator(`.dlg [data-document="${path}"]`).click();
  await expect(page.locator(`.gcanvas[data-canvas="${path}"]`)).toBeVisible();
}

function panel(page: Page): ReturnType<Page['locator']> {
  return page.locator('.panel .panel-body');
}

test.describe('a workspace fetched from an address', () => {
  test('opens read-only, says where it came from, and holds every file its manifest declares', async ({
    page,
  }) => {
    await open(page);
    await openWorkspace(page, WORKSPACE_URL);

    // The workspace is the set, and the model it holds opens — with the template document the
    // reference base pins beside it, which is outside the base and inside the set, exactly as it
    // is in the repository's own `data/`.
    await expect(page.locator('footer.status [data-workspace]')).toHaveText(WORKSPACE);
    await openDocument(page, MODEL);
    await expect(page.locator('nav.tabs .tab')).toHaveCount(1);

    // And the chrome says what it is (§4.3's banner rule, which a document's own view carries).
    const banner = page.locator('.banner.info');
    await expect(banner).toContainText(`Fetched from ${WORKSPACE_URL}vendor.json`);
    await expect(banner).toContainText('checked against the sha256 its manifest declares');
  });

  test('is judged with the base standing at the path the document pins, and not before', async ({
    page,
  }) => {
    await open(page);
    await openWorkspace(page, WORKSPACE_URL);
    await openDocument(page, MODEL);

    // Before: the document pins `../lab-base/`, which the set does not hold. The loader's own
    // words, in the tools' wording — the editor invents nothing here.
    const missing = panel(page).locator('.prow[data-source="library"]').first();
    await expect(missing).toBeVisible({ timeout: 60_000 });
    await expect(missing).toContainText(`primitive library base '${BASE}' does not exist (V1)`);

    // After: the base is fetched from its own address and stands at the path the document pins.
    // The dialog proposes that path from the address itself, and this takes the proposal.
    await openBase(page, BASE_URL);
    await expect(page.locator('.dlg')).toHaveCount(0);

    await expect(page.locator('.bar [data-pill="validation"]')).toHaveText('no problems', {
      timeout: 60_000,
    });
    await expect(page.locator('.bar [data-pill="derivation"]')).toHaveText('derived · fresh', {
      timeout: 60_000,
    });
    await expect(panel(page).locator('.prow')).toHaveCount(0);

    // And the products are the core's: the four figures §4.2 names, over a document whose
    // primitive came from an address.
    await expect(page.locator('footer.status .fig.d b').first()).not.toBeEmpty();
  });

  test('comes back after a reload, with the base still standing where it stood', async ({ page }) => {
    await open(page);
    await openWorkspace(page, WORKSPACE_URL);
    await openDocument(page, MODEL);
    await openBase(page, BASE_URL);
    await expect(page.locator('.bar [data-pill="validation"]')).toHaveText('no problems', {
      timeout: 60_000,
    });

    await page.reload();
    await expect(page.locator('#root')).toHaveAttribute('data-documents', 'ready');
    // The address was remembered, so the workspace is fetched again with no gesture at all — and
    // so is the base standing in it, which is what makes the document's pin resolve.
    await expect(page.locator('footer.status [data-workspace]')).toHaveText(WORKSPACE, {
      timeout: 60_000,
    });
    await expect(page.locator('.bar [data-pill="validation"]')).toHaveText('no problems', {
      timeout: 60_000,
    });
    await expect(panel(page).locator('.prow')).toHaveCount(0);
  });

  test('opens from the cache with its age when the address answers nothing', async ({ page }) => {
    await open(page);
    await openWorkspace(page, WORKSPACE_URL);
    await openDocument(page, MODEL);
    await openBase(page, BASE_URL);
    await expect(page.locator('.bar [data-pill="validation"]')).toHaveText('no problems', {
      timeout: 60_000,
    });

    // The host goes away. Everything the page has of it is what it cached — the whole set, each
    // file already checked against its digest when it was fetched.
    await page.route(`${publishedOrigin}/**`, (route) => route.abort('failed'));
    await page.reload();
    await expect(page.locator('#root')).toHaveAttribute('data-documents', 'ready');

    const banner = page.locator('.banner.warn');
    await expect(banner).toContainText(`Nothing answered at ${WORKSPACE_URL}vendor.json`, {
      timeout: 60_000,
    });
    await expect(banner).toContainText('this is the copy in your browser');
    await expect(banner).toContainText('ago');
    // Never silently stale: the age is on the banner, and the document is still judged — with the
    // base that was cached with it.
    await expect(page.locator('.bar [data-pill="validation"]')).toHaveText('no problems', {
      timeout: 60_000,
    });
  });
});

test.describe('a set that cannot be trusted or cannot be reached', () => {
  test('refuses a file whose sha256 disagrees, naming the path, and opens none of it', async ({
    page,
  }) => {
    await open(page);
    await openWorkspace(page, WORKSPACE_URL);
    await openBase(page, `${publishedOrigin}/${CORRUPT}/`);

    // The dialog stays up with the address that was typed, and says what did not match.
    const refusal = page.locator('.dlg [data-remote-refusal="library"]');
    await expect(refusal).toContainText(CORRUPTED, { timeout: 60_000 });
    await expect(refusal).toContainText('the manifest says');
    await expect(refusal).toContainText('none of it is opened');
    // Nothing stands anywhere: a set that was not served whole is not a set.
    await expect(page.locator('.dlg [data-mounted]')).toHaveCount(0);
  });

  test('refuses a host that permits nothing, naming the header it has to send', async ({ page }) => {
    await open(page);
    await openWorkspace(page, WORKSPACE_URL);
    await openBase(page, `${publishedOrigin}/${NO_CORS}/`);

    const refusal = page.locator('.dlg [data-remote-refusal="library"]');
    await expect(refusal).toContainText('Access-Control-Allow-Origin', { timeout: 60_000 });
    await expect(refusal).toContainText(`${publishedOrigin}/${NO_CORS}/vendor.json`);
    // A browser does not tell a refused read from an unreachable host, and the message says so
    // rather than guessing which it was (feature 0.5's own reading, one host over).
    await expect(refusal).toContainText('not reachable');
  });

  test('refuses an address that publishes no manifest, saying what a published set declares', async ({
    page,
  }) => {
    await open(page);
    await openWorkspace(page, `${publishedOrigin}/nothing-here/`);
    const refusal = page.locator('.dlg [data-remote-refusal="workspace"]');
    await expect(refusal).toContainText('404', { timeout: 60_000 });
    await expect(refusal).toContainText('nothing-here/vendor.json');
    // And nothing opened: the editor is still the empty state it started in (S17).
    await expect(page.locator('.nothing h1')).toHaveText('No workspace is open.');
  });
});

test.describe('what a set costs to fetch from another origin', () => {
  test('is one request for the whole set rather than one per file, for the same bytes', async ({
    page,
  }) => {
    // Feature 2.18 measured the vendored material at **151 files, 257–275 ms one at a time
    // against 20–41 ms in four bundles**, on the page's own origin. A published set pays the same
    // arithmetic one origin further away, and the answer is the same: the manifest declares the
    // set a second time as one bundle, and the reader takes it — with every file still checked
    // against its own sha256, which is what makes the two readings comparable.
    await page.goto(platformUrl);
    await expect(page.locator('#out')).toHaveAttribute('data-state', 'ready');
    const outcome = (await page.evaluate(async (address: string) => {
      const probes = window.platformProbe as Record<string, (at: string) => Promise<unknown>>;
      return probes['published']?.(address);
    }, WORKSPACE_URL)) as { ok: boolean; detail: Record<string, unknown> };
    expect(outcome.ok, JSON.stringify(outcome.detail)).toBe(true);

    const detail = outcome.detail;
    expect(detail['files']).toBeGreaterThan(130);
    expect(detail['sameTexts']).toBe(true);
    expect(detail['sameCount']).toBe(true);
    // Two requests — the manifest and the bundle — against one per file and the manifest.
    expect(detail['bundledRequests']).toBe(2);
    expect(detail['directRequests']).toBe(Number(detail['files']) + 1);
    expect(detail['bundledMs']).toBeLessThan(Number(detail['directMs']));
    console.log(
      `published: ${String(detail['files'])} files, ${String(detail['bytes'])} bytes — ` +
        `${Number(detail['directMs']).toFixed(1)} ms in ${String(detail['directRequests'])} requests, ` +
        `${Number(detail['bundledMs']).toFixed(1)} ms in ${String(detail['bundledRequests'])}`,
    );
  });
});

test.describe('the accessibility of what this feature draws (§4.21)', () => {
  for (const theme of ['dark', 'light'] as const) {
    test(`finds none on the address dialog in the ${theme} theme`, async ({ page }) => {
      await open(page);
      if (theme === 'light') {
        await command(page, 'View', 'view.theme-light');
      }
      await openWorkspace(page, WORKSPACE_URL);
      await openDocument(page, MODEL);
      // The dialog with a refusal in it, which is the state with the most to get wrong.
      await openBase(page, `${publishedOrigin}/${CORRUPT}/`);
      await expect(page.locator('.dlg [data-remote-refusal="library"]')).toBeVisible({
        timeout: 60_000,
      });
      // Feature 2.5's own audit, with its one exemption: the wordmark is a logotype, and WCAG
      // 1.4.3 exempts "text that is part of a logo or brand name" from the contrast requirement.
      // Nothing else is excluded, and every other rule runs over it.
      const result = await new AxeBuilder({ page }).exclude('.wordmark').analyze();
      const wordmark = await new AxeBuilder({ page })
        .include('.wordmark')
        .disableRules(['color-contrast'])
        .analyze();
      expect(
        [...result.violations, ...wordmark.violations].flatMap((one) =>
          one.nodes.map((node) => `${one.id} ${node.target.join(' ')}`),
        ),
      ).toEqual([]);
    });
  }
});
